# Generated by Django 2.2.6 on 2019-10-28 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=120)),
                ('doc_address', models.CharField(max_length=120)),
                ('doc_mobile', models.BigIntegerField()),
                ('doc_speciality', models.CharField(max_length=120)),
                ('doc_experience', models.CharField(max_length=120)),
                ('doc_degree', models.CharField(max_length=120)),
                ('doc_location', models.CharField(max_length=120)),
                ('is_male', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('feed', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=120)),
                ('h_address', models.CharField(max_length=120)),
                ('h_contact', models.BigIntegerField()),
                ('h_speciality', models.CharField(max_length=120)),
                ('h_location', models.CharField(max_length=120)),
                ('h_rating', models.CharField(max_length=120)),
                ('h_noofdoctors', models.IntegerField()),
                ('h_time', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_name', models.CharField(max_length=120)),
                ('med_disaese', models.CharField(max_length=120)),
                ('med_brand', models.CharField(max_length=120)),
                ('med_dose', models.CharField(max_length=120)),
                ('is_syrup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_doctor', models.BooleanField(default=False)),
                ('tag', models.CharField(default=None, max_length=150, null=True)),
                ('profile_picture', models.ImageField(blank=True, default=None, upload_to='profiles_pictures/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=120)),
                ('query', models.CharField(max_length=200)),
                ('doc_name', models.CharField(default=None, max_length=200, null=True)),
                ('tag', models.CharField(max_length=120)),
                ('answer', models.CharField(default=None, max_length=250, null=True)),
                ('posted', models.BooleanField(default=False)),
            ],
        ),
    ]
