# Generated by Django 2.2.6 on 2019-11-05 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_consultdoctorserializer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionSerializer',
        ),
    ]
