# Generated by Django 2.2.6 on 2019-11-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_questionserializer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
