# Generated by Django 2.2.6 on 2019-11-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_resetlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='user.png', upload_to='profiles_pictures/'),
        ),
    ]
