# Generated by Django 2.2.6 on 2019-11-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191113_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profiles_pictures/user.png', upload_to='profiles_pictures/'),
        ),
    ]
