# Generated by Django 2.2.6 on 2019-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191113_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultdoctor',
            name='experience',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
