# Generated by Django 2.2.6 on 2019-11-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usertoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertoken',
            old_name='user',
            new_name='user_name',
        ),
    ]
